# Generated by Django 5.0.2 on 2024-04-24 20:12

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('creation_date', models.DateTimeField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('number_plate', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('road', models.CharField(max_length=64)),
                ('datetime_captured', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Vehicle',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=128)),
                ('ministry_type', models.CharField(blank=True, default='', max_length=128)),
                ('surname', models.CharField(blank=True, max_length=128)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.CharField(blank=True, max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('ministry_name', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.department')),
            ],
            options={
                'db_table': 'Owner',
            },
        ),
    ]
